spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springbootdemodb
        username: root
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
            database: mysql
            database-platform: org.hibernate.dialect.MySQL5Dialect

cors:
    allowed-origins: 
        - http://localhost:3000 # Replace with your frontend URL in production
    allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
    allowed-headers: 
        - Authorization
        - Content-Type
    allowed-credentials: true
    max-age: 3600

springdoc:
  swagger-ui:
    path: /docs/index.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json

logging:
  config: classpath:logback-spring.xml
  level:
    com.example.webapp: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: Course Platform API
      description: A RESTful API for managing courses, authors, schools, and students.
      version: 1.0.0
      contact: vamsi.doddapaneni@outlook.com